language: r
cache: packages
pandoc_version: 1.19.2.1

before_install:
  - sudo apt-get install ruby-full build-essential zlib1g-dev
  - sudo apt-get install libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg
  - sudo apt-get install libgmp3-dev
  - gem install jekyll bundler
  - bundle install

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
